### ISSUE TITLE
key error 'nodes' in single node setup

### ISSUE THREAD

**Issue by harisrinivaas** [brunopsoares/prometheus_couchbase_exporter#5]
root@ubuntu:/usr/local/couchdb# prometheus-couchbase-exporter -c http://localhost:8091

Response Status (404): {"error":"not_found","reason":"Database does not exist."}

Response Status (404): {"error":"not_found","reason":"Database does not exist."}

Traceback (most recent call last):
  File "/usr/local/bin/prometheus-couchbase-exporter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/prometheus_couchbase_exporter/__init__.py", line 125, in main
    REGISTRY.register(CouchbaseCollector(args.couchbase))
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 50, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 86, in _get_names
    for metric in desc_func():
  File "/usr/local/lib/python2.7/dist-packages/prometheus_couchbase_exporter/__init__.py", line 89, in collect
    self._collect_metrics(api_key, api_values, couchbase_data)
  File "/usr/local/lib/python2.7/dist-packages/prometheus_couchbase_exporter/__init__.py", line 70, in _collect_metrics
    for node in couchbase_data['nodes']:
KeyError: 'nodes'

**Comment by brunopsoares** [comment]
Hi,
Couldn't replicate this error.
Can you give more details about it?

Btw, sorry for this delay...
